export default {
  name: 'caseStudy',
  title: 'Case Study',
  type: 'document',
  fields: [
    { name: 'client',        title: 'Client Name',                              type: 'string' },
    { name: 'slug',          title: 'Slug',                                     type: 'slug',    options: { source: 'client' } },
    { name: 'order',         title: 'Display Order',                            type: 'number' },
    { name: 'heading',       title: 'Card Heading',                             type: 'string' },
    { name: 'subtitle',      title: 'Card Subtitle',                            type: 'string' },
    { name: 'excerpt',       title: 'Excerpt',                                  type: 'text',    rows: 3 },
    { name: 'category',      title: 'Category (filter key)',                    type: 'string',  options: { list: ['hospitality', 'retail', 'aviation', 'finance'] } },
    { name: 'categoryLabel', title: 'Category Label (display)',                 type: 'string' },
    { name: 'cardStyle',     title: 'Card Style',                               type: 'string',  options: { list: [{ title: 'Large (hero)', value: 'large' }, { title: 'Compact (box)', value: 'compact' }] }, initialValue: 'large' },
    { name: 'featured',      title: 'Featured',                                 type: 'boolean', initialValue: false },
    { name: 'imageAlign',    title: 'Image Alignment',                          type: 'string',  options: { list: ['left', 'right'] }, initialValue: 'left' },
    { name: 'icon',          title: 'Icon (Material Symbol name, compact only)', type: 'string' },
    { name: 'pageFile',      title: 'Page URL path (e.g. portfolio-changi.html)', type: 'string' },
    { name: 'stat1Value',    title: 'Stat 1 Value',                             type: 'string' },
    { name: 'stat1Label',    title: 'Stat 1 Label',                             type: 'string' },
    { name: 'stat2Value',    title: 'Stat 2 Value',                             type: 'string' },
    { name: 'stat2Label',    title: 'Stat 2 Label',                             type: 'string' },
    { name: 'listingImage',  title: 'Listing Image (archive card)',             type: 'image',   options: { hotspot: true } },
    { name: 'heroImage',     title: 'Hero Image (page hero)',                   type: 'image',   options: { hotspot: true } },
    { name: 'logo',          title: 'Client Logo (white/light version)',        type: 'image',   options: { hotspot: false } },
    { name: 'bodyImages',    title: 'Body Images (in order)',                   type: 'array',   of: [{ type: 'image', options: { hotspot: true } }] },
  ],
  orderings: [
    { title: 'Display Order', name: 'orderAsc', by: [{ field: 'order', direction: 'asc' }] },
  ],
}
